Update merge-playlists.yml

diff --git a/.github/workflows/merge-playlists.yml b/.github/workflows/merge-playlists.yml
--- a/.github/workflows/merge-playlists.yml
+++ b/.github/workflows/merge-playlists.yml
@@ -23,6 +23,7 @@ jobs:
           curl -fsSL "https://raw.githubusercontent.com/drmlive/fancode-live-events/main/fancode.m3u" -o external_fancode.m3u || echo "Fancode playlist failed"
           curl -fsSL "https://raw.githubusercontent.com/abid58b/WillowLivePlaylist/refs/heads/main/willowlive.m3u" -o external_willow.m3u || echo "Willow playlist failed"
           curl -fsSL "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/z5.m3u" -o external_z5.m3u || echo "Z5 playlist failed"
+          curl -fsSL "https://raw.githubusercontent.com/himanshu-temp/m3u/refs/heads/main/sony.m3u" -o external_sony.m3u || echo "Sony playlist failed"
 
       - name: Filter and Prefix jstar.m3u Groups
         run: |
@@ -52,6 +53,8 @@ jobs:
           [ -f external_willow.m3u ] && cat external_willow.m3u >> merged_playlist.m3u
           echo "# --- Z5 Playlist ---" >> merged_playlist.m3u
           [ -f external_z5.m3u ] && cat external_z5.m3u >> merged_playlist.m3u
+          echo "# --- Sony Playlist ---" >> merged_playlist.m3u
+          [ -f external_sony.m3u ] && cat external_sony.m3u >> merged_playlist.m3u
           echo "# --- Local Playlist ---" >> merged_playlist.m3u
           cat localnetwork/my_playlist.m3u >> merged_playlist.m3u
 
@@ -61,7 +64,7 @@ jobs:
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add merged_playlist.m3u
           if ! git diff --cached --quiet; then
-            git commit -m "Ultimate update merged playlist with Willow, JStar, and Z5"
+            git commit -m "Ultimate update merged playlist with Willow, JStar, Z5, and Sony"
             git pull origin main --rebase
             git push origin main
           else
